### ISSUE TITLE
samba412 broken in 2021Q4 binary packages

### ISSUE THREAD

**Issue by timdarbydotnet** [DragonFlyBSD/DPorts#222] opened 2021-12-03 19:37 UTC
The update to samba412-4.12.15_2 completely broke my samba server. I'm trying to troubleshoot it but no success so far and not seeing anything like this in google search. This is the first time I've used pkg upgrade -fy to upgrade packages, fyi. Normally, I run pkg upgrade, if that matters. Is there a way to roll back?

❯ smbclient -L boojum.timdarby.net -W team
Enter TEAM\tim's password: 
session setup failed: NT_STATUS_UNEXPECTED_IO_ERROR

❯ smbclient //boojum.timdarby.net/m -W team
Enter TEAM\tim's password: 
tree connect failed: NT_STATUS_NO_MEMORY

**Comment by tuxillo** [comment] 2021-12-03 20:07
With regards to using `pkg upgrade -fy`, what it does basically is to reinstall everything again. Since we've switched from LibreSSL to OpenSSL, that was a must.

Which Samba version were you using before? What's that server you're trying to access, Windows, Linux, DragonFly?

**Comment by timdarbydotnet** [comment] 2021-12-03 20:19
It was either 4.12.15 or 4.12.15_1. Pretty sure it was 4.12.15_1 since I try to stat current on pkg updates. The client machine is a RPi4 running Ubuntu Server. I get the same errors if I run those smbclient commands locally on the DragonFly machine.

**Comment by tuxillo** [comment] 2021-12-03 20:33
So if the client is Ubuntu, I should assume the server is DragonFly?
Is there any debugging you can enable in Samba? I'm not very familiar with it. If you can't find it, I guess I can do some sort of test setup and try to reproduce it.

**Comment by timdarbydotnet** [comment] 2021-12-03 20:45
Yes, the server is Dragonfly 6.1. I've enabled debugging but the messages are not helpful, although I think I see where it's failing. I'm going to try making a clean install somewhere and see what happens. Can this be rolled back? I'd rather just get it working if I can and figure this out later.

**Comment by tuxillo** [comment] 2021-12-03 20:58
I don't know at this point, since the base version (4.12.15) is the same since July.

**Comment by timdarbydotnet** [comment] 2021-12-03 21:06
Right, the base version is what I want to roll back to.

**Comment by tuxillo** [comment] 2021-12-03 22:21
No, what I mean is that the version has not changed for months. It's been 4.12.15 since July and it is now, too

**Comment by timdarbydotnet** [comment] 2021-12-03 22:42
4.12.15_2 is the same as 4.12.15?

**Comment by tuxillo** [comment] 2021-12-03 22:44
Yes, they are based on the same samba version. In any case, let me know if you find out something and, if not, give me enough information so that I can reproduce the issue myself.

**Comment by timdarbydotnet** [comment] 2021-12-04 16:24
I'm going to switch to email because my reply may be too long for here, but the summary of what I've found so far is that samba appears to be corrupting its own tdb files (stored in /var/db/samba). The samba package pulls in a large number of dependencies and I'm wondering if one of them is causing the problem? I'll try to do that clean install today also.

**Comment by timdarbydotnet** [comment] 2021-12-04 23:32
I tried a new install of DF 6.0.1 and the samba package appears to be working. I'm going to try a snapshot of latest now.

**Comment by timdarbydotnet** [comment] 2021-12-04 23:50
Ok, it fails on DF latest :)

**Comment by tuxillo** [comment] 2021-12-05 12:21
I've read your email, I'll see if I can find out what's the issue.

**Comment by tuxillo** [comment] 2021-12-09 18:29
dillon fixed it in https://github.com/DragonFlyBSD/DragonFlyBSD/commit/b256c8e35e8710a5a4544d000b29b46518765bc8.

There's a warning in the commit message:

```
* Should fix samba, however any tdb databases that were created are
  probably corrupt so you may need to rm -rf /var/db/samba4, restart
  samba, and re-create your smb passwords.
```

Just upgrade to latest master and it should be fixed, thanks for taking the time!

**Closed by tuxillo** 2021-12-09 18:29 UTC

**Comment by timdarbydotnet** [comment] 2021-12-09 19:05
Thanks to both you and Dillon!
