### ISSUE TITLE
fish shell doesn't work as installed

### ISSUE THREAD

**Issue by phma** [DragonFlyBSD/DPorts#127] opened 2014-12-30 12:53 UTC
I ran "pkg ins fish" and installed fish. Then I ran fish. (You have to type /usr/local/bin/fish . If you type "fish", you get /usr/games/fish, which is the Go Fish game.) It says "fish:" and accepts input, but does nothing. It does not appear to exit when I type ^D or ^C, but whatever I type after ^D is eaten not by fish but by my usual shell once I kill the fish.
fish on Ubuntu Linux gives a prompt "phma@caracal /v/w/W/src>" and runs commands like any other shell.

**Comment by jrmarino** [comment] 2015-01-01 17:14
i think somebody will have to tell us how to fix this runtime issue (e.g. provide patches). We can mark it "broken" so it doesn't build at all, but a problem like this requires significant troubleshooting -- something a user is more motivated to provide.

**Comment by phma** [comment] 2015-01-01 23:40
On Thursday, January 01, 2015 09:15:00 jrmarino wrote:
> i think somebody will have to tell us how to fix this runtime issue (e.g.
> provide patches). We can mark it "broken" so it doesn't build at all, but a
> problem like this requires significant troubleshooting -- something a user
> is more motivated to provide.

I tried to build the package (having already installed it) and got this:

===>  Installing for p5-Locale-gettext-1.05_4
===>  Checking if p5-Locale-gettext already installed
===>   Registering installation for p5-Locale-gettext-1.05_4 as automatic
pkg-static: Unable to access file /usr/obj/dports/devel/p5-Locale-
gettext/work/stage/usr/local/lib/perl5/site_perl/mach/5.16/auto/Locale/gettext/gettext.so: 
No such file or directory
pkg-static: Unable to access file /usr/obj/dports/devel/p5-Locale-
gettext/work/stage/usr/local/lib/perl5/site_perl/mach/5.16/Locale/gettext.pm: 
No such file or directory
pkg-static: Unable to access file /usr/obj/dports/devel/p5-Locale-
gettext/work/stage/usr/local/lib/perl5/site_perl/man/man3/Locale::gettext.3.gz: 
No such file or directory
*** Error code 74

Stop.
make[5]: stopped in /usr/dports/devel/p5-Locale-gettext
*** Error code 1

Stop.
make[4]: stopped in /usr/dports/misc/help2man
*** Error code 1

Stop.
make[3]: stopped in /usr/dports/misc/help2man
*** Error code 1

Stop.
make[2]: stopped in /usr/dports/devel/autoconf
*** Error code 1

Stop.
make[1]: stopped in /usr/dports/shells/fish
*** Error code 1

Stop.
make: stopped in /usr/dports/shells/fish

So I installed the p5-Locale-gettext binary package, tried again, and got 
another error trying to build help2man. So I installed that, and tried again, 
and it appears to be building fish.

**Comment by jrmarino** [comment] 2015-01-02 00:14
you're clearly mixing ports and packages that shouldn't be mixed.  Or more correctly, you are failing to rebuild dependencies when required.  You should be using ports-mgmt/poudriere to build fish to ensure all dependencies are correct.

**Comment by phma** [comment] 2015-01-02 00:26
On Thursday, January 01, 2015 16:14:17 jrmarino wrote:
> you're clearly mixing ports and packages that shouldn't be mixed.  Or more
> correctly, you are failing to rebuild dependencies when required.  You
> should be using ports-mgmt/poudriere to build fish to ensure all
> dependencies are correct.

I'm trying to build the fish package in such a way that I can debug it. 
Apparently help2man is needed to build the package, but not to install or run 
it.

I updated the binary packages recently and it reinstalled all sorts of things 
because of dependencies.
-- 
gau do li'i co'e kei do

**Comment by jrmarino** [comment] 2015-01-02 00:41
you didn't reinstall enough.  the default perl is 5.18 and this is looking for perl 5.16, so your perl packages are apparently mixed.

**Comment by phma** [comment] 2015-01-02 00:48
On Thursday, January 01, 2015 16:41:59 jrmarino wrote:
> you didn't reinstall enough.  the default perl is 5.18 and this is looking
> for perl 5.16, so your perl packages are apparently mixed.
# pkg sea perl
...
perl2html-0.9.2_1
perl5-5.18.4_10
perl5.14-5.14.4_13
perl5.16-5.16.3_17
perl5.20-5.20.1_9
perlconsole-0.4_2
...

5.16.3 is what's installed. I don't see 5.18.

Apparently perl is needed just to make the man page, and the problem is in the 
executable. How do I build an executable that has debugging symbols using pkg?

Pierre
-- 
Jews use a lunisolar calendar; Muslims use a solely lunar calendar.

**Comment by jrmarino** [comment] 2015-01-02 01:58
I really don't want to try to trouble live system building.  It's discouraged, there are way too many variables and misinformation.  This clearly builds in a proper environment since a binary package exists.

I recommend "poudriere testport -i" which will build the port and drop into the build via chroot which should serve to test a port.

**Comment by phma** [comment] 2015-01-02 14:36
On Thursday, January 01, 2015 17:58:15 jrmarino wrote:
> I really don't want to try to trouble live system building.  It's
> discouraged, there are way too many variables and misinformation.  This
> clearly builds in a proper environment since a binary package exists.
> 
> I recommend "poudriere testport -i" which will build the port and drop into
> the build via chroot which should serve to test a port.

I made a jail and tried to run the testport command. Here's what I got:

# poudriere testport -ij aoeu -o shells/fish
cat: /usr/local/etc/poudriere.d/ports/default/mnt: No such file or directory
====>> Creating the reference jail.../etc/resolv.conf -> 
/usr/local/poudriere/data/build/aoeu-default/ref/etc/resolv.conf
====>> Mounting system devices for aoeu-default
====>> Mounting ports/packages/distfiles
cat: /usr/local/etc/poudriere.d/ports/default/mnt: No such file or directory
====>> Mounting packages from: /usr/local/poudriere/data/packages/aoeu-default
usage: mount_null [-o options] target_fs mount_point
       mount_null -u [-o options] mount_point
====>> Error: Failed to mount the ports directory 
====>> Cleaning up
exit: cannot create /usr/local/poudriere/data/logs/bulk/aoeu-
default/20150102_143306/.poudriere.epoch: No such file or directory
====>> Umounting file systems

-- 
Jews use a lunisolar calendar; Muslims use a solely lunar calendar.

**Comment by jrmarino** [comment] 2015-01-02 20:54
what do you mean by "made a jail"?  Do you mean you literally are using dragonfly jails with poudriere?  If so, that's incorrect usage.  poudriere doesn't work in a jail (and there's no reason to run it inside a jail).

**Comment by phma** [comment] 2015-01-02 20:59
On Friday, January 02, 2015 12:54:39 jrmarino wrote:
> what do you mean by "made a jail"?  Do you mean you literally are using
> dragonfly jails with poudriere?  If so, that's incorrect usage.  poudriere
> doesn't work in a jail (and there's no reason to run it inside a jail).

I used the poudriere jail command.
# poudriere jail -cj aoeu
This took some hours to build world and download ports.
-- 
La sal en el mar es más que en la sangre.
Le sel dans la mer est plus que dans le sang.

**Comment by jrmarino** [comment] 2015-01-02 21:05
okay, that sounds right.
Maybe you already have some things mounted.  Does "mount" show any leftover mounts?
Maybe you can just reboot the server and try again to be sure nothing is blocking the mounts.

**Comment by phma** [comment] 2015-01-02 21:11
On Friday, January 02, 2015 13:05:42 jrmarino wrote:
> okay, that sounds right.
> Maybe you already have some things mounted.  Does "mount" show any leftover
> mounts? Maybe you can just reboot the server and try again to be sure
> nothing is blocking the mounts.

Nothing's mounted except the usual filesystems.
-- 
ve ka'a ro klaji la .romas. se jmaji

**Comment by jrmarino** [comment] 2015-01-02 21:20
"poudriere testport -j aoeu -i -vn -o shells/fish" should work (notice the -n switch).  If it doesn't, try rebooting and try again.  If it still doesn't work, I'm stumped as to why it fails.

Unless you didn't create a ports tree?????

Did you run "poudriere ports -c" command already?

**Comment by jrmarino** [comment] 2015-01-20 09:27
what is the current status here?  Did you create a ports tree  before trying to build the package?

**Comment by phma** [comment] 2015-01-20 09:43
I got some likely paying work and haven't had time to work on the fish. I'm 
also leaving (hopefully today) for a trip and won't be able to work on it 
until I get back, or next week.

Now the objective of this exercise is to get a fish binary that is not stripped 
and that I can debug. Is there a flag I can set to make it not strip the 
binary?
-- 
The gostak pelled at the fostin lutt for darfs for her martle plave.
The darfs had smibbed, the lutt was thale, and the pilter had nothing snave.

**Comment by jrmarino** [comment] 2015-01-20 10:18
With poudriere, you can define a makefile that gets applied to specific jail/tree combinations.
So for example, you would add "WITH_DEBUG=yes" and poudriere would add that to the make.conf that it uses (and thus fish would not be stripped).

It takes one command to add a ports tree.  I was only asking if you issued that command.  If you didn't, that's why poudriere failed to mount.

**Comment by phma** [comment] 2015-01-29 14:57
# poudriere ports -c
====>> Cloning the ports tree via git
====>> Generating ports top level and category makefiles.
# poudriere testport -j aoeu -i -vn -o shells/fish
====>> Creating the reference jail.../etc/resolv.conf -> 
/usr/local/poudriere/data/build/aoeu-default/ref/etc/resolv.conf
====>> Mounting system devices for aoeu-default
====>> Mounting ports/packages/distfiles
====>> Mounting packages from: /usr/local/poudriere/data/packages/aoeu-default
====>> Logs: /usr/local/poudriere/data/logs/bulk/aoeu-default/20150129_135958
====>> Loading MOVED
====>> Calculating ports order and dependencies
====>> Computing deps for ports-mgmt/pkg====>> Computing deps for devel/gmake

====>> Computing deps for devel/gettext-tools
====>> Computing deps for devel/autoconf
====>> Computing deps for textproc/expat2
====>> Computing deps for devel/m4
====>> Computing deps for devel/gettext-runtime
====>> Computing deps for print/indexinfo
====>> Computing deps for misc/help2man
====>> Computing deps for devel/p5-Locale-gettext
====>> Computing deps for lang/perl5.18
====>> Computing deps for devel/gmake-lite
====>> Computing deps for devel/autoconf-wrapper
====>> pkg package missing, skipping sanity
====>> Cleaning the build queue
====>> Recording filesystem state for prepkg... done
====>> Building 13 packages using 2 builders
====>> Starting/Cloning builders
====>> Hit CTRL+t at any time to see build progress and stats
====>> [01] Starting build of ports-mgmt/pkg
====>> [01] Jail     Mounting
====>> [01] Jail     Ready
====>> [01] Status   ports-mgmt/pkg: check-config
====>> [01] Status   ports-mgmt/pkg: pkg-depends
====>> [01] Status   ports-mgmt/pkg: fetch-depends
====>> [01] Status   ports-mgmt/pkg: fetch
====>> [01] Status   ports-mgmt/pkg: checksum
====>> [01] Status   ports-mgmt/pkg: distfiles
====>> [01] Status   ports-mgmt/pkg: extract-depends
====>> [01] Status   ports-mgmt/pkg: extract
====>> [01] Status   ports-mgmt/pkg: patch-depends
====>> [01] Status   ports-mgmt/pkg: patch
====>> [01] Status   ports-mgmt/pkg: build-depends
====>> [01] Status   ports-mgmt/pkg: lib-depends
====>> [01] Status   ports-mgmt/pkg: configure
====>> [01] Status   ports-mgmt/pkg: build
====>> [01] Status   ports-mgmt/pkg: run-depends
====>> [01] Status   ports-mgmt/pkg: stage
====>> [01] Status   ports-mgmt/pkg: package
====>> [01] Status   ports-mgmt/pkg: install-mtree
====>> [01] Status   ports-mgmt/pkg: install
====>> [01] Finished ports-mgmt/pkg: Success
====>> [01] Starting build of print/indexinfo
====>> [01] Jail     Renovating
====>> [02] Starting build of lang/perl5.18
====>> [02] Jail     Mounting
====>> [01] Jail     Ready
====>> [02] Jail     Ready
====>> [01] Status   print/indexinfo: check-config
====>> [01] Status   print/indexinfo: pkg-depends
====>> [02] Status   lang/perl5.18: check-config
====>> [02] Status   lang/perl5.18: pkg-depends
====>> [01] Status   print/indexinfo: fetch-depends
====>> [01] Status   print/indexinfo: fetch
====>> [02] Status   lang/perl5.18: fetch-depends
====>> [02] Status   lang/perl5.18: fetch
====>> [01] Status   print/indexinfo: checksum
====>> [01] Status   print/indexinfo: distfiles
====>> [01] Status   print/indexinfo: extract-depends
====>> [01] Status   print/indexinfo: extract
====>> [02] Status   lang/perl5.18: checksum
====>> [01] Status   print/indexinfo: patch-depends
====>> [01] Status   print/indexinfo: patch
====>> [01] Status   print/indexinfo: build-depends
====>> [01] Status   print/indexinfo: lib-depends
====>> [01] Status   print/indexinfo: configure
====>> [01] Status   print/indexinfo: build
====>> [01] Status   print/indexinfo: run-depends
====>> [01] Status   print/indexinfo: stage
====>> [01] Status   print/indexinfo: package
====>> [01] Status   print/indexinfo: install-mtree
====>> [01] Status   print/indexinfo: install
====>> [02] Status   lang/perl5.18: distfiles
====>> [02] Status   lang/perl5.18: extract-depends
====>> [02] Status   lang/perl5.18: extract
====>> [01] Finished print/indexinfo: Success
====>> [01] Starting build of devel/gettext-runtime
====>> [01] Jail     Renovating
====>> [01] Jail     Ready
====>> [01] Status   devel/gettext-runtime: check-config
====>> [01] Status   devel/gettext-runtime: pkg-depends
====>> [01] Status   devel/gettext-runtime: fetch-depends
====>> [01] Status   devel/gettext-runtime: fetch
====>> [01] Status   devel/gettext-runtime: checksum
====>> [02] Status   lang/perl5.18: patch-depends
====>> [02] Status   lang/perl5.18: patch
====>> [02] Status   lang/perl5.18: build-depends
====>> [02] Status   lang/perl5.18: lib-depends
====>> [02] Status   lang/perl5.18: configure
====>> [01] Status   devel/gettext-runtime: distfiles
====>> [01] Status   devel/gettext-runtime: extract-depends
====>> [01] Status   devel/gettext-runtime: extract
====>> [01] Status   devel/gettext-runtime: patch-depends
====>> [01] Status   devel/gettext-runtime: patch
====>> [01] Status   devel/gettext-runtime: build-depends
====>> [01] Status   devel/gettext-runtime: lib-depends
====>> [01] Status   devel/gettext-runtime: configure
====>> [01] Status   devel/gettext-runtime: build
====>> [02] Status   lang/perl5.18: build
====>> [01] Status   devel/gettext-runtime: run-depends
====>> [01] Status   devel/gettext-runtime: stage
====>> [01] Status   devel/gettext-runtime: package
====>> [01] Status   devel/gettext-runtime: install-mtree
====>> [01] Status   devel/gettext-runtime: install
====>> [01] Finished devel/gettext-runtime: Success
====>> [01] Starting build of textproc/expat2
====>> [01] Jail     Renovating
====>> [01] Jail     Ready
====>> [01] Status   textproc/expat2: check-config
====>> [01] Status   textproc/expat2: pkg-depends
====>> [01] Status   textproc/expat2: fetch-depends
====>> [01] Status   textproc/expat2: fetch
====>> [01] Status   textproc/expat2: checksum
====>> [01] Status   textproc/expat2: distfiles
====>> [01] Status   textproc/expat2: extract-depends
====>> [01] Status   textproc/expat2: extract
====>> [01] Status   textproc/expat2: patch-depends
====>> [01] Status   textproc/expat2: patch
====>> [01] Status   textproc/expat2: build-depends
====>> [01] Status   textproc/expat2: lib-depends
====>> [01] Status   textproc/expat2: configure
====>> [01] Status   textproc/expat2: build
====>> [01] Status   textproc/expat2: run-depends
====>> [01] Status   textproc/expat2: stage
====>> [01] Status   textproc/expat2: package
====>> [01] Status   textproc/expat2: install-mtree
====>> [01] Status   textproc/expat2: install
====>> [01] Finished textproc/expat2: Success
====>> [01] Starting build of devel/gettext-tools
====>> [01] Jail     Renovating
====>> [01] Jail     Ready
====>> [01] Status   devel/gettext-tools: check-config
====>> [01] Status   devel/gettext-tools: pkg-depends
====>> [01] Status   devel/gettext-tools: fetch-depends
====>> [01] Status   devel/gettext-tools: fetch
====>> [01] Status   devel/gettext-tools: checksum
====>> [01] Status   devel/gettext-tools: distfiles
====>> [01] Status   devel/gettext-tools: extract-depends
====>> [01] Status   devel/gettext-tools: extract
====>> [01] Status   devel/gettext-tools: patch-depends
====>> [01] Status   devel/gettext-tools: patch
====>> [01] Status   devel/gettext-tools: build-depends
====>> [01] Status   devel/gettext-tools: lib-depends
====>> [01] Status   devel/gettext-tools: configure
====>> [01] Status   devel/gettext-tools: build
====>> [01] Status   devel/gettext-tools: run-depends
====>> [01] Status   devel/gettext-tools: stage
====>> [01] Status   devel/gettext-tools: package
====>> [01] Status   devel/gettext-tools: install-mtree
====>> [01] Status   devel/gettext-tools: install
====>> [01] Finished devel/gettext-tools: Success
====>> [01] Starting build of devel/m4
====>> [01] Jail     Renovating
====>> [01] Jail     Ready
====>> [01] Status   devel/m4: check-config
====>> [01] Status   devel/m4: pkg-depends
====>> [01] Status   devel/m4: fetch-depends
====>> [01] Status   devel/m4: fetch
====>> [01] Status   devel/m4: checksum
====>> [01] Status   devel/m4: distfiles
====>> [01] Status   devel/m4: extract-depends
====>> [01] Status   devel/m4: extract
====>> [01] Status   devel/m4: patch-depends
====>> [01] Status   devel/m4: patch
====>> [01] Status   devel/m4: build-depends
====>> [01] Status   devel/m4: lib-depends
====>> [01] Status   devel/m4: configure
====>> [01] Status   devel/m4: build
====>> [01] Status   devel/m4: run-depends
====>> [01] Status   devel/m4: stage
====>> [01] Status   devel/m4: package
====>> [01] Status   devel/m4: install-mtree
====>> [01] Status   devel/m4: install
====>> [01] Finished devel/m4: Success
====>> [01] Starting build of devel/autoconf-wrapper
====>> [01] Jail     Renovating
====>> [01] Jail     Ready
====>> [01] Status   devel/autoconf-wrapper: check-config
====>> [01] Status   devel/autoconf-wrapper: pkg-depends
====>> [01] Status   devel/autoconf-wrapper: fetch-depends
====>> [01] Status   devel/autoconf-wrapper: fetch
====>> [01] Status   devel/autoconf-wrapper: checksum
====>> [01] Status   devel/autoconf-wrapper: distfiles
====>> [01] Status   devel/autoconf-wrapper: extract-depends
====>> [01] Status   devel/autoconf-wrapper: extract
====>> [01] Status   devel/autoconf-wrapper: patch-depends
====>> [01] Status   devel/autoconf-wrapper: patch
====>> [01] Status   devel/autoconf-wrapper: build-depends
====>> [01] Status   devel/autoconf-wrapper: lib-depends
====>> [01] Status   devel/autoconf-wrapper: configure
====>> [01] Status   devel/autoconf-wrapper: build
====>> [01] Status   devel/autoconf-wrapper: run-depends
====>> [01] Status   devel/autoconf-wrapper: stage
====>> [01] Status   devel/autoconf-wrapper: package
====>> [01] Status   devel/autoconf-wrapper: install-mtree
====>> [01] Status   devel/autoconf-wrapper: install
====>> [01] Finished devel/autoconf-wrapper: Success
====>> [01] Starting build of devel/gmake
====>> [01] Jail     Renovating
====>> [01] Jail     Ready
====>> [01] Status   devel/gmake: check-config
====>> [01] Status   devel/gmake: pkg-depends
====>> [01] Status   devel/gmake: fetch-depends
====>> [01] Status   devel/gmake: fetch
====>> [02] Status   lang/perl5.18: run-depends
====>> [02] Status   lang/perl5.18: stage
====>> [01] Status   devel/gmake: checksum
====>> [01] Status   devel/gmake: distfiles
====>> [01] Status   devel/gmake: extract-depends
====>> [01] Status   devel/gmake: extract
====>> [01] Status   devel/gmake: patch-depends
====>> [01] Status   devel/gmake: patch
====>> [01] Status   devel/gmake: build-depends
====>> [01] Status   devel/gmake: lib-depends
====>> [01] Status   devel/gmake: configure
====>> [01] Status   devel/gmake: build
====>> [01] Status   devel/gmake: run-depends
====>> [01] Status   devel/gmake: stage
====>> [01] Status   devel/gmake: package
====>> [01] Status   devel/gmake: install-mtree
====>> [01] Status   devel/gmake: install
====>> [01] Finished devel/gmake: Success
====>> [01] Starting build of devel/gmake-lite
====>> [01] Jail     Renovating
====>> [01] Jail     Ready
====>> [01] Status   devel/gmake-lite: check-config
====>> [01] Status   devel/gmake-lite: pkg-depends
====>> [01] Status   devel/gmake-lite: fetch-depends
====>> [01] Status   devel/gmake-lite: fetch
====>> [01] Status   devel/gmake-lite: checksum
====>> [01] Status   devel/gmake-lite: distfiles
====>> [01] Status   devel/gmake-lite: extract-depends
====>> [01] Status   devel/gmake-lite: extract
====>> [01] Status   devel/gmake-lite: patch-depends
====>> [01] Status   devel/gmake-lite: patch
====>> [01] Status   devel/gmake-lite: build-depends
====>> [01] Status   devel/gmake-lite: lib-depends
====>> [01] Status   devel/gmake-lite: configure
====>> [01] Status   devel/gmake-lite: build
====>> [01] Status   devel/gmake-lite: run-depends
====>> [01] Status   devel/gmake-lite: stage
====>> [01] Status   devel/gmake-lite: package
====>> [01] Status   devel/gmake-lite: install-mtree
====>> [01] Status   devel/gmake-lite: install
====>> [01] Finished devel/gmake-lite: Success
====>> [02] Status   lang/perl5.18: package
====>> [02] Status   lang/perl5.18: install-mtree
====>> [02] Status   lang/perl5.18: install
====>> [02] Finished lang/perl5.18: Success
====>> [01] Starting build of devel/p5-Locale-gettext
====>> [01] Jail     Renovating
====>> [01] Jail     Ready
====>> [01] Status   devel/p5-Locale-gettext: check-config
====>> [01] Status   devel/p5-Locale-gettext: pkg-depends
====>> [01] Status   devel/p5-Locale-gettext: fetch-depends
====>> [01] Status   devel/p5-Locale-gettext: fetch
====>> [01] Status   devel/p5-Locale-gettext: checksum
====>> [01] Status   devel/p5-Locale-gettext: distfiles
====>> [01] Status   devel/p5-Locale-gettext: extract-depends
====>> [01] Status   devel/p5-Locale-gettext: extract
====>> [01] Status   devel/p5-Locale-gettext: patch-depends
====>> [01] Status   devel/p5-Locale-gettext: patch
====>> [01] Status   devel/p5-Locale-gettext: build-depends
====>> [01] Status   devel/p5-Locale-gettext: lib-depends
====>> [01] Status   devel/p5-Locale-gettext: configure
====>> [01] Status   devel/p5-Locale-gettext: build
====>> [01] Status   devel/p5-Locale-gettext: run-depends
====>> [01] Status   devel/p5-Locale-gettext: stage
====>> [01] Status   devel/p5-Locale-gettext: package
====>> [01] Status   devel/p5-Locale-gettext: install-mtree
====>> [01] Status   devel/p5-Locale-gettext: install
====>> [01] Finished devel/p5-Locale-gettext: Success
====>> [01] Starting build of misc/help2man
====>> [01] Jail     Renovating
====>> [01] Jail     Ready
====>> [01] Status   misc/help2man: check-config
====>> [01] Status   misc/help2man: pkg-depends
====>> [01] Status   misc/help2man: fetch-depends
====>> [01] Status   misc/help2man: fetch
====>> [01] Status   misc/help2man: checksum
====>> [01] Status   misc/help2man: distfiles
====>> [01] Status   misc/help2man: extract-depends
====>> [01] Status   misc/help2man: extract
====>> [01] Status   misc/help2man: patch-depends
====>> [01] Status   misc/help2man: patch
====>> [01] Status   misc/help2man: build-depends
====>> [01] Status   misc/help2man: lib-depends
====>> [01] Status   misc/help2man: configure
====>> [01] Status   misc/help2man: build
====>> [01] Status   misc/help2man: run-depends
====>> [01] Status   misc/help2man: stage
====>> [01] Status   misc/help2man: package
====>> [01] Status   misc/help2man: install-mtree
====>> [01] Status   misc/help2man: install
====>> [01] Finished misc/help2man: Success
====>> [01] Starting build of devel/autoconf
====>> [01] Jail     Renovating
====>> [01] Jail     Ready
====>> [01] Status   devel/autoconf: check-config
====>> [01] Status   devel/autoconf: pkg-depends
====>> [01] Status   devel/autoconf: fetch-depends
====>> [01] Status   devel/autoconf: fetch
====>> [01] Status   devel/autoconf: checksum
====>> [01] Status   devel/autoconf: distfiles
====>> [01] Status   devel/autoconf: extract-depends
====>> [01] Status   devel/autoconf: extract
====>> [01] Status   devel/autoconf: patch-depends
====>> [01] Status   devel/autoconf: patch
====>> [01] Status   devel/autoconf: build-depends
====>> [01] Status   devel/autoconf: lib-depends
====>> [01] Status   devel/autoconf: configure
====>> [01] Status   devel/autoconf: build
====>> [01] Status   devel/autoconf: run-depends
====>> [01] Status   devel/autoconf: stage
====>> [01] Status   devel/autoconf: package
====>> [01] Status   devel/autoconf: install-mtree
====>> [01] Status   devel/autoconf: install
====>> [01] Finished devel/autoconf: Success
====>> Stopping 2 builders
====>> Creating pkgng repository
====>> Cleaning up
====>> Umounting file systems

It does not say that it built fish. What am I missing?
-- 
gau do li'i co'e kei do

**Comment by jrmarino** [comment] 2015-01-31 21:14
I don't know.  I just tried a very similar command and shell/fish built in testport without any issue.

**Comment by jrmarino** [comment] 2015-03-20 08:34
Is fish still broken?  If so, I will remove it from dports with a "broken" mask.

**Comment by cgag** [comment] 2015-04-12 05:43
I just ran into this.  I'm on 4.0.5-release.

**Comment by jrmarino** [comment] 2015-04-18 13:23
maybe this patch will fix it?
https://svnweb.freebsd.org/ports?view=revision&revision=384226

**Comment by jrmarino** [comment] 2015-05-06 12:58
can somebody let me know if this is fixed now?

**Comment by jrmarino** [comment] 2015-05-17 06:14
Closing under the assumption the issue is fixed.

**Closed by jrmarino** 2015-05-17 06:14 UTC
