### ISSUE TITLE
Asterisk problem

### ISSUE THREAD

**Issue by bluesun08** [DragonFlyBSD/DPorts#161] opened 2015-08-16 00:11 UTC
Error loading module 'chan_sip.so': Undefined symbol "_nss_cache_cycle_prevention_function"

**Comment by jrmarino** [comment] 2016-04-16 07:15
It's a huge turn off to get problem reports the comprise entirely of a pasted error message.  It tells the reader that the submitter has no interested in spending a nanosecond in providing vital details, e.g. how to reproduce, what options were set, etc.  Yet at the same time, it's a request that the reader spend tons of time trying to fix it, even without full details.

Above is just feedback in case you do this sort of thing on other bug lists, mail list etc.  It's a great way for reports to be ignored (e.g. if you don't care much, why should I?).

if you want to continue with this:
1) confirm that it's still happening on current ports
2) Provide full details on what actions you took to get there, what options you set (if any) and any other information you feel a tester might need to know.  

At least then I could determine if it's a dragonfly problem, port problem, dports problem, etc...

**Comment by jrmarino** [comment] 2016-06-09 09:08
Due to lack of details on what options were selected, how to reproduced, and lack of follow-up, I'm closing the PR.

**Closed by jrmarino** 2016-06-09 09:08 UTC
