### ISSUE TITLE
pkg check -Ba and net/libproxy graphics/graphite2 required shared library libstdc++.so.9 not found

### ISSUE THREAD

**Issue by davshao** [DragonFlyBSD/DPorts#110] opened 2014-08-30 01:30 UTC
Building ports / dports from source, I followed FreeBSD's ports advice 

      # make -C /usr/ports/ports-mgmt/pkg build deinstall install clean
      # pkg check -Ba

But unlike FreeBSD 11-current, pkg check -Ba and reinstalling net/libproxy and graphics/graphite2 does nothing about the messages:

```
# pkg check -Ba
Checking all packages:  26%
pkg: (graphite2-1.2.4) /usr/local/bin/gr2fonttest - required shared library libstdc++.so.9 not found
Checking all packages:  48%
pkg: (libproxy-0.4.6) /usr/local/bin/proxy - required shared library libstdc++.so.9 not found

# cd /usr/local/bin
# ldd gr2fonttest
gr2fonttest:
	libgraphite2.so.3 => /usr/local/lib/libgraphite2.so.3 (0x80082f000)
	libstdc++.so.9 => not found (0)
	libm.so.4 => /lib/libm.so.4 (0x800a5c000)
	libc.so.8 => /lib/libc.so.8 (0x800c86000)
	libstdc++.so.9 => /usr/lib/gcc47/libstdc++.so.9 (0x800fdb000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x8012e3000)
```
I even rebuilt devel/cmake beforehand.

**Comment by jrmarino** [comment] 2015-02-03 21:47
I tried "pkg check -Ba" with version 1.4.7 on the package set on muscles, everything worked fine.  I don't know if there's still a problem or not, but there haven't been any other complaints.

I think I'll close this ticket for now (can't reproduce? obsolete?) but if you think it's still an issue, feel free to reopen the issue.

**Closed by jrmarino** 2015-02-03 21:47 UTC
